name: Atualizar posts do blog

on:
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://lucianareginarocha.com.br/rss.xml"
          max_post_count: 3
